[2025-08-22T06:07:31.735+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-22T06:07:31.969+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_etl_pipeline.load__1 scheduled__2025-08-21T00:00:00+00:00 [queued]>
[2025-08-22T06:07:32.002+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_etl_pipeline.load__1 scheduled__2025-08-21T00:00:00+00:00 [queued]>
[2025-08-22T06:07:32.003+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-22T06:07:32.031+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load__1> on 2025-08-21 00:00:00+00:00
[2025-08-22T06:07:32.037+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2025-08-22T06:07:32.044+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_etl_pipeline', 'load__1', 'scheduled__2025-08-21T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/fetch_stock_prices.py', '--cfg-path', '/tmp/tmp3yu5qkog']
[2025-08-22T06:07:32.048+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask load__1
[2025-08-22T06:07:32.154+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_etl_pipeline.load__1 scheduled__2025-08-21T00:00:00+00:00 [running]> on host 45b0b72cb42c
[2025-08-22T06:07:32.346+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_etl_pipeline' AIRFLOW_CTX_TASK_ID='load__1' AIRFLOW_CTX_EXECUTION_DATE='2025-08-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-21T00:00:00+00:00'
[2025-08-22T06:07:32.347+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-22T06:07:32.350+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-22T06:07:32.351+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_stock_prices.py", line 45, in load
    from scripts.db_utils import upsert_rows
ModuleNotFoundError: No module named 'scripts.db_utils'
[2025-08-22T06:07:32.366+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_etl_pipeline, task_id=load__1, run_id=scheduled__2025-08-21T00:00:00+00:00, execution_date=20250821T000000, start_date=20250822T060731, end_date=20250822T060732
[2025-08-22T06:07:32.378+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task load__1 (No module named 'scripts.db_utils'; 189)
[2025-08-22T06:07:32.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-22T06:07:32.418+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T06:07:32.419+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
