[2025-08-22T06:07:31.763+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-22T06:07:32.000+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_etl_pipeline.load scheduled__2025-08-21T00:00:00+00:00 [queued]>
[2025-08-22T06:07:32.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_etl_pipeline.load scheduled__2025-08-21T00:00:00+00:00 [queued]>
[2025-08-22T06:07:32.024+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-22T06:07:32.053+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-08-21 00:00:00+00:00
[2025-08-22T06:07:32.058+0000] {standard_task_runner.py:63} INFO - Started process 190 to run task
[2025-08-22T06:07:32.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_etl_pipeline', 'load', 'scheduled__2025-08-21T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/fetch_stock_prices.py', '--cfg-path', '/tmp/tmpxr3ogjlb']
[2025-08-22T06:07:32.069+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load
[2025-08-22T06:07:32.178+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_etl_pipeline.load scheduled__2025-08-21T00:00:00+00:00 [running]> on host 45b0b72cb42c
[2025-08-22T06:07:32.353+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-08-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-21T00:00:00+00:00'
[2025-08-22T06:07:32.354+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-22T06:07:32.355+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-22T06:07:32.355+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_stock_prices.py", line 45, in load
    from scripts.db_utils import upsert_rows
ModuleNotFoundError: No module named 'scripts.db_utils'
[2025-08-22T06:07:32.369+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_etl_pipeline, task_id=load, run_id=scheduled__2025-08-21T00:00:00+00:00, execution_date=20250821T000000, start_date=20250822T060732, end_date=20250822T060732
[2025-08-22T06:07:32.381+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task load (No module named 'scripts.db_utils'; 190)
[2025-08-22T06:07:32.414+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-22T06:07:32.437+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T06:07:32.439+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
